package:
  name: qtawesome
  version: 0.3.2

source:
  fn: QtAwesome-0.3.2.tar.gz
  url: https://pypi.python.org/packages/source/Q/QtAwesome/QtAwesome-0.3.2.tar.gz
  md5: 0644cc006a2cce95dfa3871a22e4a444

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - qtpy
    - six

test:
  requires:
    - pyqt
  imports:
    - qtawesome

about:
  home: https://github.com/spyder-ide/qtawesome
  license: MIT
  summary: FontAwesome icons in PyQt and PySide applications
