package:
  name: pytz
  version: 2016.2

source:
  fn: pytz-2016.2.tar.bz2
  url: https://pypi.python.org/packages/source/p/pytz/pytz-2016.2.tar.bz2
  md5: fb1567d323ed403e939d5e3f699880cd

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - pytz

about:
  home: http://pytz.sourceforge.net/
  license: MIT
  license_file: LICENSE.txt
  summary: World timezone definitions, modern and historical
