package:
  name: pexpect
  version: 4.0.1

source:
  fn: pexpect-4.0.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pexpect/pexpect-4.0.1.tar.gz
  md5: 056df81e6ca7081f1015b4b147b977b7

requirements:
  build:
    - python
  run:
    - python
    - ptyprocess >=0.5

test:
  imports:
    - pexpect

about:
  home: http://pexpect.readthedocs.org/
  license: ISC
  license_family: Other
  license_file: LICENSE
  summary: Pexpect allows easy control of interactive console applications
