package:
  name: pyflakes
  version: 1.1.0

source:
  fn: pyflakes-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pyflakes/pyflakes-1.1.0.tar.gz
  md5: e0bf854cd5abd4527e149692925b82eb

build:
  entry_points:
    - pyflakes = pyflakes.api:main

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - pyflakes test_file.py      [not (win and py3k)]
    - pyflakes --version
  files:
    - test_file.py

about:
  home: https://launchpad.net/pyflakes
  license: MIT
  license_file: LICENSE
  summary: passive checker of Python programs
