package:
  name: decorator
  version: 4.0.9

source:
  fn: decorator-4.0.9.tar.gz
  url: https://pypi.python.org/packages/source/d/decorator/decorator-4.0.9.tar.gz
  md5: f12c5651ccd707e12a0abaa4f76cd69a

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - decorator

about:
  home: http://pypi.python.org/pypi/decorator
  license: BSD
  license_file: LICENSE.txt
  summary: Better living through Python with decorators
