package:
  name: jupyter_core
  version: 4.1.0

source:
  fn: jupyter_core-4.1.0.tar.gz
  url: https://pypi.python.org/packages/source/j/jupyter_core/jupyter_core-4.1.0.tar.gz
  md5: 78f6add824eef72b12e0f6e6940372b3

requirements:
  build:
    - python
  run:
    - python
    - traitlets

test:
  commands:
    - jupyter -h
    - jupyter-migrate -h
  imports:
    - jupyter_core
    - jupyter_core.utils

about:
  home: http://jupyter.org
  license: BSD
  summary: base package on which Jupyter projects rely
