package:
  name: ipykernel
  version: 4.3.1

source:
  fn: ipykernel-4.3.1.tar.gz
  url: https://pypi.python.org/packages/source/i/ipykernel/ipykernel-4.3.1.tar.gz
  md5: 0b1150602203af298631555509a809bd

requirements:
  build:
    - python
  run:
    - python
    - ipython >=4.0
    - traitlets
    - jupyter_client
    - tornado >=4.0

test:
  imports:
    - ipykernel

about:
  home: http://ipython.org
  license: BSD
  summary: IPython Kernel for Jupyter
