package:
  name: nltk
  version: "3.2"

source:
  fn: nltk-3.2.tar.gz
  url: https://pypi.python.org/packages/source/n/nltk/nltk-3.2.tar.gz
  md5: cec19785ffd176fa6d18ef41a29eb227

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - nltk

about:
  home: http://nltk.org/
  license: Apache
  license_file: LICENSE.txt
  summary: Natural Language Toolkit
