package:
  name: colorama
  version: 0.3.7

source:
  fn: colorama-0.3.7.tar.gz
  url: https://pypi.python.org/packages/source/c/colorama/colorama-0.3.7.tar.gz
  md5: 349d2b02618d3d39e5c6aede36fe3c1a

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - colorama

about:
  home: http://code.google.com/p/colorama/
  license: BSD
  license_file: LICENSE.txt
  summary: Cross-platform colored terminal text.
