package:
  name: werkzeug
  version: 0.11.4

source:
  fn: Werkzeug-0.11.4.tar.gz
  url: https://pypi.python.org/packages/source/W/Werkzeug/Werkzeug-0.11.4.tar.gz
  md5: 9c5cfb704e39aea1524777caa5891eb0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - werkzeug

about:
  home: http://werkzeug.pocoo.org/
  license: BSD
  license_file: LICENSE
  summary: The Swiss Army knife of Python web development
