package:
  name: ipython
  version: 4.1.2

source:
  fn: ipython-4.1.2.tar.gz
  url: https://pypi.python.org/packages/source/i/ipython/ipython-4.1.2.tar.gz
  md5: 28c9ebd1abfb9b4a07cb87005f285edd

build:
  number: 1
  entry_points:
    - ipython = IPython:start_ipython
    - ipython2 = IPython:start_ipython   [py2k]
    - ipython3 = IPython:start_ipython   [py3k]
  osx_is_app: True

requirements:
  build:
    - python
  run:
    - python
    - decorator
    - pickleshare
    - simplegeneric >0.8
    - traitlets
    - pexpect                [unix]
    - appnope                [osx]
    - pyreadline             [win]
    - python.app             [osx]

test:
  commands:
    - ipython -h
    - ipython2 -h            [py2k]
    - ipython3 -h            [py3k]
  imports:
    - IPython

about:
  home: http://ipython.org/
  license: BSD
  license_file: COPYING.rst
  summary: Productive Interactive Computing
