package:
  name: spyder
  version: 2.3.8

source:
  fn: spyder-2.3.8.zip
  url: https://pypi.python.org/packages/source/s/spyder/spyder-2.3.8.zip
  md5: fb890dc956f606c43d560558159f3491

build:
  number: 1
  osx_is_app: True

requirements:
  build:
    - python
  run:
    - python
    - pyqt
    - rope
    - pyflakes
    - jedi >=0.8
    - qtconsole
    - nbconvert
    - pygments
    - sphinx
    - pep8
    - psutil
    - python.app      [osx]

app:
  entry: spyder
  icon: logo.png
  summary: Scientific Python Development Environment
  type: desk

test:
  commands:
    - spyder -h
  imports:
    - spyderlib

about:
  home: https://github.com/spyder-ide/spyder
  license: MIT
  license_file: LICENSE
  summary: Scientific PYthon Development EnviRonment
