package:
  name: gevent
  version: 1.1.0

source:
  fn: gevent-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/g/gevent/gevent-1.1.0.tar.gz
  md5: 24b3e44134fbff250526f3b949763f99

requirements:
  build:
    - python
    - setuptools           [win]
    - greenlet >=0.4.9     [win]
  run:
    - python
    - greenlet >=0.4.9

test:
  imports:
    - gevent

about:
  home: http://www.gevent.org/
  license: MIT
  license_file: LICENSE
  summary: Coroutine-based network library
